const $=s=>document.querySelector(s);const STORAGE="energy-certificate-draft-v1";
const basic=[
 {id:"name",label:"Rakennuksen nimi energiatodistukseen",required:true},{id:"address",label:"Osoite ja postinumero",required:true},
 {id:"year",label:"Rakennusvuosi",type:"number",min:1700,max:2100,required:true},{id:"propertyId",label:"Kiinteistötunnus",placeholder:"49-10-2-1",required:true},
 {id:"buildingId",label:"Rakennustunnus",placeholder:"101562527J"},{id:"araSupport",label:"Haetaanko kohteelle ARAn energiatukea",type:"select",options:["Ei","Kyllä"]}
];
const building=[
 {id:"heatedArea",label:"Lämpimät tilat, nettoala",type:"number",unit:"m²",required:true},{id:"semiHeatedArea",label:"Puolilämpimät tilat, nettoala",type:"number",unit:"m²"},
 {id:"volume",label:"Ilmatilavuus",type:"number",unit:"m³",required:true},{id:"floors",label:"Kerrosten lukumäärä",type:"number",unit:"kerrosta",required:true},
 {id:"airLeak",label:"Ilmanvuotoluku q50",type:"number",unit:"m³/(h m²)",help:"Jos arvo on alle 4, se tulee todeta mittaamalla."}
];
const hvac=[
 {id:"primaryHeat",label:"Ensisijainen lämmöntuottojärjestelmä",required:true},{id:"secondaryHeat",label:"Toissijainen lämmöntuottojärjestelmä"},{id:"heatDistribution",label:"Lämmönjakojärjestelmä",required:true},
 {id:"bathroomHeat",label:"Märkätiloissa sähköinen mukavuuslämmitys",type:"select",options:["Ei","Kyllä"]},{id:"hotWaterLoop",label:"Lämpimän käyttöveden kierto",type:"select",options:["Ei","Kyllä"]},
 {id:"towelRadiators",label:"Vesikiertoiset rättipatterit, lukumäärä ja teho",placeholder:"esim. 2 kpl, 60 W/kpl"},{id:"pressureValve",label:"Vesijohdossa paineenalennusventtiili",type:"select",options:["Ei","Kyllä","Ei tiedossa"]},
 {id:"storage",label:"Varaajien tilavuus ja eristepaksuus"},{id:"ventilation",label:"Ilmanvaihtojärjestelmä",required:true},{id:"supplyHeat",label:"Tuloilman lämmityksen lämmönlähde"},
 {id:"heatRecovery",label:"Lämmöntalteenoton vuosihyötysuhde",type:"number",unit:"%"},{id:"sfp",label:"Ilmanvaihtojärjestelmän SFP-luku",type:"number",unit:"kW/(m³/s)"},{id:"exhaustMin",label:"Jäteilman alin mahdollinen lämpötila",type:"number",unit:"°C"}
];
const electrical=[{id:"lighting",label:"Valaistuksen tehotiheys",type:"number",unit:"W/m²",help:"Energiaselvityksen liitteeksi voidaan tarvita erillinen laskelma."},{id:"solar",label:"Aurinkopaneelien laajuus",type:"number",unit:"kWp"}];
const structureNames=["Ulkoseinä","Yläpohja","Alapohja","Ovet"];
const directions=["Pohjoinen","Koillinen","Itä","Kaakko","Etelä","Lounas","Länsi","Luode"];
const bridges=["Ulkoseinän ja yläpohjan liitos","Ulkoseinän ja välipohjan liitos","Ulkoseinän ja alapohjan liitos","Ulkoseinien välinen liitos, ulkonurkka","Ulkoseinien välinen liitos, sisänurkka","Ulkoseinien ja ikkunoiden ja ovien liitos"];
const sections=[
 {id:"identity",title:"Kohteen tiedot",help:"Rakennuksen yksilöinti",fields:basic},
 {id:"building",title:"Rakennuksen perustiedot",help:"Laajuus ja ilmanpitävyys",fields:building},
 {id:"systems",title:"LVI-järjestelmät",help:"Lämmitys, käyttövesi ja ilmanvaihto",fields:hvac},
 {id:"electric",title:"Sähkötekniset järjestelmät",help:"Valaistus ja paikallinen sähköntuotanto",fields:electrical},
 {id:"structures",title:"Rakennetekniset tiedot",help:"Lisää rakennetyypit pinta-aloineen ja U-arvoineen",repeat:"structures"},
 {id:"windows",title:"Ikkunat ilmansuunnittain",help:"Syötä vähintään pinta-alat sekä tunnetut U- ja g-arvot",repeat:"windows"},
 {id:"bridges",title:"Kylmäsillat",help:"Uudisrakennuksessa kylmäsiltojen pituudet tulee laskea",repeat:"bridges"},
 {id:"notes",title:"Lisätiedot",help:"Havainnot, tietolähteet ja laatijalle välitettävät huomiot",fields:[{id:"notes",label:"Lisätiedot",type:"textarea",full:true}]}
];
let state=load(),step=0;
function initial(){return {type:"new",values:{},structures:Object.fromEntries(structureNames.map(n=>[n,[{}]])),windows:Object.fromEntries(directions.map(n=>[n,{}])),bridges:Object.fromEntries(bridges.map(n=>[n,""]))};}
function load(){try{return {...initial(),...JSON.parse(localStorage.getItem(STORAGE)||"null")};}catch{return initial();}}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state));$("#saveStatus").textContent="Tallennettu laitteelle";updateProgress();}
function activeSections(){return sections.filter(s=>!(s.id==="bridges"&&state.type!=="new"));}
function fieldVisible(f){if(f.id==="buildingId"||f.id==="araSupport")return state.type!=="new";return true;}
function render(){const list=activeSections();step=Math.min(step,list.length-1);$("#formType").value=state.type;renderStepper(list);renderSection(list[step]);renderSummary();updateProgress();$("#previousButton").disabled=step===0;$("#nextButton").style.display=step===list.length-1?"none":"inline-flex";}
function renderStepper(list){$("#stepper").innerHTML=list.map((s,i)=>`<button type="button" data-step="${i}" class="${i===step?"active":""}">${i+1}. ${s.title}</button>`).join("");}
function renderSection(s){const form=$("#energyForm");form.innerHTML=`<section class="form-card"><h2>${s.title}</h2><p class="section-help">${s.help}</p><div class="fields"></div></section>`;const box=form.querySelector(".fields");if(s.fields)s.fields.filter(fieldVisible).forEach(f=>box.append(makeField(f)));if(s.repeat==="structures")box.append(renderStructures());if(s.repeat==="windows")box.append(renderWindows());if(s.repeat==="bridges")box.append(renderBridges());}
function makeField(f){const el=$("#fieldTemplate").content.firstElementChild.cloneNode(true);if(f.full)el.classList.add("full");const label=el.querySelector("label");label.textContent=f.label+(f.unit?` (${f.unit})`:"");label.htmlFor=f.id;if(f.required)label.classList.add("required");let input;if(f.type==="select"){input=document.createElement("select");input.innerHTML='<option value="">Valitse…</option>'+f.options.map(x=>`<option>${x}</option>`).join("");}else if(f.type==="textarea")input=document.createElement("textarea");else{input=document.createElement("input");input.type=f.type||"text";if(f.type==="number"){input.step="any";input.inputMode="decimal";}["min","max","placeholder"].forEach(k=>{if(f[k]!=null)input[k]=f[k]});}input.id=f.id;input.name=f.id;input.value=state.values[f.id]??"";input.required=!!f.required;el.querySelector(".control").append(input);el.querySelector("small").textContent=f.help||"";return el;}
function renderStructures(){const wrap=document.createElement("div");wrap.className="repeat";wrap.innerHTML=structureNames.map(name=>`<div class="repeat-toolbar"><h3>${name}</h3><button type="button" data-add="${name}">+ Lisää rivi</button></div><div class="repeat-list" data-structure="${name}">${(state.structures[name]||[{}]).map((r,i)=>structureRow(name,r,i)).join("")}</div>`).join("");return wrap;}
function structureRow(name,r,i){return `<div class="repeat-row"><input class="wide" data-k="description" data-group="${name}" data-i="${i}" value="${esc(r.description)}" placeholder="Rakennemateriaali / kuvaus"><input data-k="area" data-group="${name}" data-i="${i}" value="${esc(r.area)}" type="number" step="any" inputmode="decimal" placeholder="Pinta-ala m²"><input data-k="u" data-group="${name}" data-i="${i}" value="${esc(r.u)}" type="number" step="any" inputmode="decimal" placeholder="U-arvo"><select data-k="boundary" data-group="${name}" data-i="${i}"><option value="">Rajautuu…</option><option ${r.boundary==="Ulkoilma"?"selected":""}>Ulkoilma</option><option ${r.boundary==="Puolilämmin tila"?"selected":""}>Puolilämmin tila</option></select><span></span><button class="remove" type="button" data-remove="${name}" data-i="${i}" aria-label="Poista rivi">×</button></div>`;}
function renderWindows(){const wrap=document.createElement("div");wrap.className="repeat";wrap.innerHTML=`<div class="repeat-list">${directions.map(n=>{const r=state.windows[n]||{};return `<div class="repeat-row"><strong>${n}</strong><input data-window="${n}" data-k="area" value="${esc(r.area)}" type="number" step="any" placeholder="Pinta-ala m²"><input data-window="${n}" data-k="u" value="${esc(r.u)}" type="number" step="any" placeholder="U-arvo"><input data-window="${n}" data-k="g" value="${esc(r.g)}" type="number" step="any" placeholder="g-arvo"><input class="wide" data-window="${n}" data-k="shade" value="${esc(r.shade)}" placeholder="Varjostus"><span></span></div>`}).join("")}</div>`;return wrap;}
function renderBridges(){const wrap=document.createElement("div");wrap.className="repeat";wrap.innerHTML=`<div class="repeat-list">${bridges.map(n=>`<div class="field"><label>${n} (m)</label><input data-bridge="${n}" value="${esc(state.bridges[n])}" type="number" step="any" inputmode="decimal"></div>`).join("")}</div>`;return wrap;}
function esc(v){return String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));}
function num(v){const n=Number(String(v??"").replace(",","."));return Number.isFinite(n)?n:0;}
function metrics(){let area=0,heatLoss=0;Object.values(state.structures).flat().forEach(r=>{area+=num(r.area);heatLoss+=num(r.area)*num(r.u)});const windowArea=Object.values(state.windows).reduce((a,r)=>a+num(r.area),0);return{area,weightedU:area?heatLoss/area:0,windowArea};}
function requiredMissing(){return [...basic,...building,...hvac].filter(f=>f.required&&fieldVisible(f)&&!String(state.values[f.id]??"").trim()).map(f=>f.label);}
function renderSummary(){const m=metrics(),missing=requiredMissing();$("#summary").innerHTML=`<h2>Yhteenveto</h2><div class="summary-grid"><div class="metric"><span>Rakenteet</span><strong>${m.area.toFixed(1)} m²</strong></div><div class="metric"><span>Painotettu U-arvo</span><strong>${m.weightedU?m.weightedU.toFixed(3):"–"}</strong></div><div class="metric"><span>Ikkunat</span><strong>${m.windowArea.toFixed(1)} m²</strong></div><div class="metric"><span>Pakollisia puuttuu</span><strong>${missing.length}</strong></div></div>${missing.length?`<p class="issues"><strong>Täydennä:</strong> ${missing.join(", ")}</p>`:"<p>Pakolliset perustiedot on täytetty.</p>"}<p><small>Laskettu rakenteisiin lisätyistä riveistä. Painotettu U-arvo = Σ(pinta-ala × U-arvo) / Σ(pinta-ala).</small></p>`;}
function updateProgress(){const fields=[...basic,...building,...hvac,...electrical].filter(fieldVisible),filled=fields.filter(f=>String(state.values[f.id]??"").trim()).length,pct=Math.round(filled/fields.length*100);$("#progress").value=pct;$("#progressLabel").textContent=`${pct} % täytetty`;}
$("#energyForm").addEventListener("input",e=>{const t=e.target;if(t.dataset.group){const r=state.structures[t.dataset.group][+t.dataset.i];r[t.dataset.k]=t.value;}else if(t.dataset.window){state.windows[t.dataset.window][t.dataset.k]=t.value;}else if(t.dataset.bridge){state.bridges[t.dataset.bridge]=t.value;}else if(t.name)state.values[t.name]=t.value;$("#saveStatus").textContent="Tallennetaan…";save();renderSummary();});
$("#energyForm").addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;if(b.dataset.add){state.structures[b.dataset.add].push({});save();render();}if(b.dataset.remove){state.structures[b.dataset.remove].splice(+b.dataset.i,1);if(!state.structures[b.dataset.remove].length)state.structures[b.dataset.remove].push({});save();render();}});
$("#stepper").addEventListener("click",e=>{const b=e.target.closest("button");if(b){step=+b.dataset.step;render();scrollTo({top:130,behavior:"smooth"});}});
$("#formType").addEventListener("change",e=>{state.type=e.target.value;step=0;save();render();});
$("#previousButton").onclick=()=>{step=Math.max(0,step-1);render();scrollTo({top:130,behavior:"smooth"});};$("#nextButton").onclick=()=>{step=Math.min(activeSections().length-1,step+1);render();scrollTo({top:130,behavior:"smooth"});};
$("#printButton").onclick=()=>window.print();$("#menuButton").onclick=()=>{const n=$("#actions"),open=n.classList.toggle("open");$("#menuButton").setAttribute("aria-expanded",open)};
$("#newButton").onclick=()=>{if(confirm("Tyhjennetäänkö nykyisen kohteen tiedot?")){state=initial();step=0;save();render();}};
$("#exportButton").onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`energiatiedot-${state.values.propertyId||"kohde"}.json`;a.click();URL.revokeObjectURL(a.href);};
$("#importInput").onchange=async e=>{try{state={...initial(),...JSON.parse(await e.target.files[0].text())};step=0;save();render();}catch{alert("Tiedostoa ei voitu lukea energiatietojen JSON-tiedostona.");}};
if("serviceWorker" in navigator&&location.protocol.startsWith("http"))navigator.serviceWorker.register("sw.js");render();
